name: Test Badge Maker
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: ./
      with:
        text: '⭐ Tested!'
    - uses: stefanzweifel/git-auto-commit-action@v5
